//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistikmäklaren.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Företag.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Våra intressenter.
        /// </summary>
        internal static string customerbar_supporters {
            get {
                return ResourceManager.GetString("customerbar_supporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förnamn.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flakmeter.
        /// </summary>
        internal static string flakmeter {
            get {
                return ResourceManager.GetString("flakmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godset skall skickas efter.
        /// </summary>
        internal static string Godset_skall_skickas_efter {
            get {
                return ResourceManager.GetString("Godset_skall_skickas_efter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godset skall vara framme senast.
        /// </summary>
        internal static string Godset_skall_vara_framme_senast {
            get {
                return ResourceManager.GetString("Godset_skall_vara_framme_senast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godsinformation.
        /// </summary>
        internal static string Godsinformation {
            get {
                return ResourceManager.GetString("Godsinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolli.
        /// </summary>
        internal static string Kolli {
            get {
                return ResourceManager.GetString("Kolli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternamn.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga av.
        /// </summary>
        internal static string logonpartial_logoff {
            get {
                return ResourceManager.GetString("logonpartial_logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        internal static string logonpartial_logon {
            get {
                return ResourceManager.GetString("logonpartial_logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny Användare.
        /// </summary>
        internal static string logonpartial_register {
            get {
                return ResourceManager.GetString("logonpartial_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paket.
        /// </summary>
        internal static string Paket {
            get {
                return ResourceManager.GetString("Paket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pall.
        /// </summary>
        internal static string Pall {
            get {
                return ResourceManager.GetString("Pall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallplats.
        /// </summary>
        internal static string pallplats {
            get {
                return ResourceManager.GetString("pallplats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om logistikmäklaren.
        /// </summary>
        internal static string Sitemap_about {
            get {
                return ResourceManager.GetString("Sitemap_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allmän information om logistikmäklaren och moderprojektet North East Cargo Link II.
        /// </summary>
        internal static string Sitemap_about_desc {
            get {
                return ResourceManager.GetString("Sitemap_about_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Sitemap_information {
            get {
                return ResourceManager.GetString("Sitemap_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information om Logistikmäklaren.
        /// </summary>
        internal static string Sitemap_information_desc {
            get {
                return ResourceManager.GetString("Sitemap_information_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string Sitemap_press {
            get {
                return ResourceManager.GetString("Sitemap_press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information till nytta för media.
        /// </summary>
        internal static string Sitemap_press_desc {
            get {
                return ResourceManager.GetString("Sitemap_press_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hem.
        /// </summary>
        internal static string Sitemap_root {
            get {
                return ResourceManager.GetString("Sitemap_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startsida för Logistikmäklaren.
        /// </summary>
        internal static string Sitemap_root_desc {
            get {
                return ResourceManager.GetString("Sitemap_root_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speditör.
        /// </summary>
        internal static string Sitemap_shippingagent {
            get {
                return ResourceManager.GetString("Sitemap_shippingagent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sida för speditörer.
        /// </summary>
        internal static string Sitemap_shippingagent_desc {
            get {
                return ResourceManager.GetString("Sitemap_shippingagent_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverantör.
        /// </summary>
        internal static string Sitemap_supplier {
            get {
                return ResourceManager.GetString("Sitemap_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sida för Leverantörer.
        /// </summary>
        internal static string Sitemap_supplier_desc {
            get {
                return ResourceManager.GetString("Sitemap_supplier_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundservice.
        /// </summary>
        internal static string Sitemap_support {
            get {
                return ResourceManager.GetString("Sitemap_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundservice.
        /// </summary>
        internal static string Sitemap_support_desc {
            get {
                return ResourceManager.GetString("Sitemap_support_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök Transport.
        /// </summary>
        internal static string Sitemap_transport {
            get {
                return ResourceManager.GetString("Sitemap_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitta en transport för vara.
        /// </summary>
        internal static string Sitemap_transport_desc {
            get {
                return ResourceManager.GetString("Sitemap_transport_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid och datum.
        /// </summary>
        internal static string Tid_och_datum {
            get {
                return ResourceManager.GetString("Tid_och_datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakta Oss!.
        /// </summary>
        internal static string topmenu_contact {
            get {
                return ResourceManager.GetString("topmenu_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frågor och svar.
        /// </summary>
        internal static string topmenu_faq {
            get {
                return ResourceManager.GetString("topmenu_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök Transport.
        /// </summary>
        internal static string Transport_sök_transport {
            get {
                return ResourceManager.GetString("Transport_sök_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamn.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volym (m&lt;sup&gt;3&lt;/sup&gt;).
        /// </summary>
        internal static string volym_m3 {
            get {
                return ResourceManager.GetString("volym_m3", resourceCulture);
            }
        }
    }
}
