//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ViewModels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta lösenord.
        /// </summary>
        internal static string ChangePasswordModel_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt lösenord.
        /// </summary>
        internal static string ChangePasswordModel_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuvarande lösenord.
        /// </summary>
        internal static string ChangePasswordModel_OldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordModel_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum:.
        /// </summary>
        internal static string TransportModel_Date {
            get {
                return ResourceManager.GetString("TransportModel_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverans:.
        /// </summary>
        internal static string TransportModel_DateRestrictionType {
            get {
                return ResourceManager.GetString("TransportModel_DateRestrictionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till:.
        /// </summary>
        internal static string TransportModel_Destination {
            get {
                return ResourceManager.GetString("TransportModel_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från:.
        /// </summary>
        internal static string TransportModel_Origin {
            get {
                return ResourceManager.GetString("TransportModel_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal kollin:.
        /// </summary>
        internal static string TransportModel_Packages {
            get {
                return ResourceManager.GetString("TransportModel_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kollityp:.
        /// </summary>
        internal static string TransportModel_PackageType {
            get {
                return ResourceManager.GetString("TransportModel_PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vikt eller volym:.
        /// </summary>
        internal static string TransportModel_SelectedVolumeType {
            get {
                return ResourceManager.GetString("TransportModel_SelectedVolumeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid:.
        /// </summary>
        internal static string TransportModel_Time {
            get {
                return ResourceManager.GetString("TransportModel_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volym:.
        /// </summary>
        internal static string TransportModel_Volume {
            get {
                return ResourceManager.GetString("TransportModel_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vikt:.
        /// </summary>
        internal static string TransportModel_Weight {
            get {
                return ResourceManager.GetString("TransportModel_Weight", resourceCulture);
            }
        }
    }
}
